// Reduced to 50 memories per character
const MEMORY_STORIES = {
    fire: [
        "Before destiny ever spoke my name, I was just another student drifting through a modern world that felt too small for the storm inside my chest.",
        "The five of us had known each other since school, bound together by boredom, laughter, and the feeling that something greater waited beyond the routine of classes and exams.",
        "Even back then, everyone knew I was the impulsive one, the guy who felt everything too strongly and reacted before thinking.",
        "Anger always came easily to me, but so did passion, and I never learned how to separate the two.",
        "My father was a firefighter, and growing up around his stories made fire feel like both a monster and a calling.",
        "I admired how he ran toward danger while others fled, and I secretly wondered if I would ever be that brave.",
        "The night my life changed, the city was swallowed by smoke and sirens as a high-rise burned out of control.",
        "I didn’t hear my own thoughts as I ran inside, only the roar of flames and the pounding of my heart.",
        "Logic said I should have died there, suffocated or burned alive before help could reach me.",
        "Instead, the fire bent away from my skin as if it recognized me.",
        "I felt heat without pain, power without destruction, and something ancient waking inside my chest.",
        "When I stepped back into the night unharmed, the flames followed me like loyal shadows.",
        "That was the moment destiny chose me, though I didn’t understand it yet.",
        "After that night, the dreams began, vivid and relentless, showing me a golden mask floating in darkness.",
        "Behind it lurked a presence that radiated fear itself, whispering my doubts back at me in my own voice.",
        "Makuta learned my name before I learned his.",
        "When I told my friends what happened, none of them laughed, and that terrified me more than disbelief ever could.",
        "Water tried to calm me with that quiet strength she always carried, even when fear trembled behind her eyes.",
        "Metal cracked jokes and flirted shamelessly with her, pretending courage was effortless.",
        "Plants listened carefully, like he was already hearing something we couldn’t.",
        "Ice dissected every detail, hoping logic could cage the impossible.",
        "My fire answered emotion, not reason, and that made me dangerous.",
        "Sometimes sparks leapt from my hands without warning, shattering windows or scorching the ground.",
        "Other times, when I needed the flames most, they refused to appear at all.",
        "The chaos inside me fed Makuta’s whispers, telling me I was unworthy of power.",
        "Then the Green Goblin attacked, crawling out of shadow with threats aimed at the people we loved.",
        "Rage consumed me in that first battle, and my flames exploded outward without control.",
        "I hurt the enemy, but I endangered civilians, and that failure burned worse than any wound.",
        "The shame nearly broke me, and Makuta pressed harder, promising that fear would always own me.",
        "Destiny sent me to my trial, a volcanic wasteland where the ground itself pulsed with molten rage.",
        "There, fire did not obey screams or fury, only intention and balance.",
        "Every reckless attack left me exhausted, buried beneath ash and doubt.",
        "Slowly, painfully, I learned to breathe before acting, to listen instead of command.",
        "Fire taught me that destruction is easy, but creation requires restraint.",
        "Lava flows with patience, unstoppable not because it rushes, but because it endures.",
        "I faced visions of everyone I feared losing, watching my own flames consume them.",
        "Each time, I chose control over impulse, even when it hurt.",
        "When I returned to my friends, my fire felt different, steadier, purposeful.",
        "In our second clash with the Green Goblin, my flames burned only what needed to fall.",
        "Watching his vines turn to ash without collateral damage felt like redemption.",
        "Still, Makuta did not retreat, because doubt is harder to kill than monsters.",
        "He whispered that control would fail me when emotions ran deepest.",
        "I still fear he might be right.",
        "Fire is honest, and it reveals weakness as easily as strength.",
        "When Metal jokes and flirts to hide his fear, I see the cracks behind his steel grin.",
        "When Water steadies us all, I feel how close I come to unraveling without her.",
        "Plants reminds me that growth comes after burning old ground away.",
        "Ice keeps me from rushing blindly into disaster.",
        "Together, we form something stronger than my flames alone.",
        "The golden mask feels warm when I draw near, like it senses my resolve growing."
    ],
    water: [
        "Before any of us were heroes, I was simply the girl who listened more than she spoke and felt more than she showed.",
        "We had been friends since school, bound by years of shared lunches, inside jokes, and dreams we never said out loud.",
        "The boys were louder, more impulsive, always competing in subtle ways they pretended didn’t matter.",
        "I learned early how to calm them, how to soften arguments before they became fights.",
        "Even then, I was already flowing between them, holding the group together without realizing it.",
        "Water had always been my refuge, long before it became my power.",
        "When life felt overwhelming, I went swimming, letting the world blur into silence beneath the surface.",
        "In water, expectations dissolved, and I could finally breathe.",
        "The day everything changed began with rain, heavy and relentless, like the sky itself was grieving.",
        "The river near town overflowed, swallowing roads, cars, and people without mercy.",
        "I was trying to help evacuate when the ground gave way beneath my feet.",
        "The current dragged me under instantly, cold and violent, stealing my breath.",
        "Panic screamed inside my chest as darkness closed in around me.",
        "Then something shifted, and the water slowed as if it had decided to spare me.",
        "I felt myself being carried, cradled, protected by the very force that should have killed me.",
        "In that moment, I heard a voice not in words, but in understanding.",
        "Water did not want to harm me.",
        "It wanted me to trust it.",
        "When I emerged downstream, unharmed, I knew my life had changed forever.",
        "Destiny does not always arrive like thunder; sometimes it arrives like a quiet current pulling you forward.",
        "When I told the others, fear rippled through the group, even when they tried to hide it.",
        "Fire looked at me like it was his fault, as if he could have stopped fate itself.",
        "Ice immediately started asking questions, desperate to anchor the impossible in logic.",
        "Plants watched me with a strange calm, like he had expected this all along.",
        "Metal smiled too widely, flirted too obviously, pretending the world hadn’t just cracked open beneath us.",
        "I teased him back, because humor felt safer than fear.",
        "My powers emerged slowly, unpredictably, tied tightly to my emotions.",
        "When I felt afraid, waves surged violently around me.",
        "When I felt sad, rain followed me like a shadow.",
        "When I felt calm, water moved with grace and precision.",
        "Makuta found me quickly, whispering that compassion would be my weakness.",
        "He told me leaders must be ruthless, and softness would doom us all.",
        "Part of me feared he was right.",
        "During our first encounter with the Green Goblin, I hesitated when I should have struck.",
        "His threats against our loved ones cut deeper than any blade.",
        "That hesitation nearly cost us everything.",
        "Destiny sent me into my trial, deep beneath the ocean’s surface where light barely reaches.",
        "Pressure crushed in from every direction, forcing me to confront my fear of drowning again.",
        "The ocean showed me memories of everyone I cared about slipping away.",
        "I learned that panic wastes strength, while calm preserves it.",
        "Water does not fight pressure; it becomes it.",
        "Slowly, I learned to let fear pass through me without taking control.",
        "I discovered that depth is not weakness, but resilience.",
        "When I returned, my water no longer lashed out blindly.",
        "It moved with intention, flowing where it was needed most.",
        "The next time we faced the Green Goblin, I did not hesitate.",
        "I trapped his roots, drowned his escape routes, and stood firm despite his threats.",
        "I saw respect in my friends’ eyes, mixed with relief.",
        "Metal flirted again, louder than ever, trying to hide how shaken he was.",
        "I smiled, because sometimes humor is how people stay afloat.",
    ],
    ice: [
        "Even before destiny intervened, I was always the one who tried to understand everything before acting.",
        "While the others laughed, argued, or dreamed aloud, I observed patterns and searched for explanations.",
        "We had been friends since school, and they accepted my quiet nature without ever questioning it.",
        "Logic felt safer than emotion, because logic never surprised me.",
        "I believed that if I could understand something well enough, it couldn’t hurt me.",
        "Cold had always fascinated me, not because it was cruel, but because it was precise.",
        "Ice does not rage or hesitate; it simply exists within strict rules.",
        "During winter, I felt clearer, sharper, more focused than at any other time.",
        "The moment my power awakened was during a sudden blackout in the middle of a snowstorm.",
        "Trapped outside, my body should have frozen within minutes.",
        "Instead, the cold wrapped around me like armor.",
        "Frost formed where my breath touched the air, obeying my thoughts rather than the weather.",
        "I felt fear, but it was distant, muted by an unfamiliar calm.",
        "That calm frightened me more than the storm.",
        "Destiny arrived not with passion, but with silence.",
        "When I told the others, Fire reacted emotionally, while Water tried to comfort me.",
        "Metal joked, as always, and Plants looked at me like he already understood the cost.",
        "I immediately began testing my limits, documenting every reaction and anomaly.",
        "Ice responded best to discipline, structure, and restraint.",
        "The more detached I became, the stronger my control grew.",
        "Makuta noticed that weakness immediately.",
        "He whispered that emotion was unnecessary, that attachment only introduced error.",
        "He offered clarity without pain.",
        "For a time, I almost believed him.",
        "Our first encounter with the Green Goblin proved how dangerous hesitation could be.",
        "I calculated optimal strategies while others acted.",
        "That delay nearly cost us lives.",
        "Failure lodged in my mind like a fracture beneath the surface.",
        "Destiny sent me to my trial, a frozen wasteland where sound itself seemed to shatter.",
        "Alone in that endless white, my thoughts grew colder.",
        "Ice obeyed perfectly, responding instantly to precise commands.",
        "But the more control I gained, the less I felt.",
        "Memories dulled, emotions slowed, and fear became distant static.",
        "Makuta’s voice grew clearer in the silence.",
        "He told me this was evolution.",
        "He told me warmth was inefficiency.",
        "I saw visions of my friends frozen in place, preserved forever, safe but lifeless.",
        "Something inside me rejected that future.",
        "Ice can preserve, but it can also shatter.",
        "I realized control without connection leads only to stillness.",
        "I forced myself to remember laughter, mistakes, and warmth.",
        "The ice cracked when I allowed emotion back in.",
        "Pain followed, sharp and immediate.",
        "That pain meant I was still human.",
        "When I returned, my power was less perfect, but more flexible.",
        "Ice now bends instead of only resisting.",
        "In our second fight with the Green Goblin, I acted without overthinking.",
        "My frost trapped him instantly, allowing my friends to finish the battle.",
        "Fire nodded at me with rare respect.",
        "Water smiled, relief visible even through exhaustion.",
    ],
    plant: [
        "I was never the loudest among us, even back in school when we still believed life would be simple.",
        "While the others argued, joked, or planned their futures, I preferred watching how things unfolded naturally.",
        "I liked understanding consequences before taking action.",
        "Plants fascinated me long before they became my power.",
        "I spent hours in gardens, forests, and parks, feeling calmer the farther I got from concrete.",
        "Growth felt honest, slow, and unavoidable.",
        "I learned early that nothing grows without taking space from something else.",
        "The day my power awakened, I was volunteering at a community garden near the edge of town.",
        "A sudden sinkhole opened beneath us, swallowing tools, soil, and people alike.",
        "Instinct took over, and I reached for the ground without thinking.",
        "Roots erupted from the earth, stopping the collapse inches from disaster.",
        "I felt life surge through my veins, ancient and patient.",
        "The plants responded like they had been waiting for me.",
        "Destiny did not feel dramatic in that moment.",
        "It felt inevitable.",
        "When I told my friends, Fire reacted with excitement and fear mixed together.",
        "Water listened carefully, already sensing the responsibility this power carried.",
        "Ice asked questions about limits and sustainability.",
        "Metal joked about free wooden armor, hiding unease behind humor.",
        "I smiled, but I already felt the weight settling on my shoulders.",
        "Plants do not choose sides; they grow wherever conditions allow.",
        "Learning to command them felt unnatural at first.",
        "Sometimes vines grew too aggressively, crushing things I meant to protect.",
        "Other times, nothing happened at all, as if nature judged me unworthy.",
        "Makuta’s whispers came softly, almost kindly.",
        "He told me growth was neutral, that morality was a human illusion.",
        "He showed me forests swallowing cities and called it balance.",
        "Part of me understood his argument.",
        "That terrified me.",
        "Our first battle with the Green Goblin shook that fear into reality.",
        "His corrupted vines mirrored my own power, twisted by cruelty.",
        "I hesitated, afraid of becoming like him.",
        "That hesitation gave him an opening.",
        "People were hurt because I doubted myself.",
        "Destiny sent me to my trial, a living jungle where everything competed for survival.",
        "There, growth was violent, relentless, and merciless.",
        "Weak plants were strangled by stronger ones without hesitation.",
        "The jungle showed me that unchecked growth is just another form of destruction.",
        "I faced visions of myself ruling nature without restraint.",
        "The image sickened me.",
        "I realized stewardship is not the same as control.",
        "Sometimes, growth must be guided.",
        "Sometimes, it must be cut back.",
        "When I accepted that responsibility, the jungle calmed.",
        "Plants obeyed not dominance, but intent.",
        "When I returned, my power felt heavier, but clearer.",
        "In our second confrontation with the Green Goblin, I did not hesitate.",
        "I severed his corrupted roots without mercy.",
        "I understood then that compassion does not mean passivity.",
        "Fire respected that decisiveness.",
    ],
    metal: [
        "I’ve always been the guy who jokes first and thinks later, mostly because silence makes fear too loud.",
        "Back in school, humor was my armor, and sarcasm was how I survived bad days.",
        "The five of us stuck together because somehow our flaws fit like puzzle pieces.",
        "Fire burned too hot, Ice thought too much, Plants felt too deeply, and Water held us all together.",
        "And me, I pretended nothing ever scared me.",
        "I flirted with Water shamelessly, partly because she smiled back, and partly because it made everything feel normal.",
        "I never meant to hide behind charm, but it became habit.",
        "Metal fascinated me long before it became my power.",
        "Machines made sense, because broken parts could be replaced.",
        "People were harder to fix.",
        "The day destiny found me, I was trapped inside a collapsing construction site.",
        "Steel beams snapped, concrete fell, and panic finally caught up with me.",
        "I tried to run, but the floor gave way beneath my feet.",
        "Pain should have followed.",
        "Instead, my body hardened.",
        "Metal fused to my skin like it had always belonged there.",
        "The falling beams bent around me, screaming under pressure.",
        "I laughed hysterically afterward, because laughing felt better than shaking.",
        "Destiny doesn’t always choose heroes; sometimes it chooses shields.",
        "When I told the others, Fire looked impressed and worried at the same time.",
        "Water touched my arm like she needed to be sure I was still human.",
        "Ice immediately asked about structural limits.",
        "Plants warned me quietly about becoming too rigid.",
        "I joked it off, because that’s what I do.",
        "At first, my powers felt amazing.",
        "Nothing could hurt me.",
        "Or so I thought.",
        "I could lift impossible weight, block massive attacks, and walk through danger smiling.",
        "Inside, though, every impact echoed.",
        "Makuta noticed that quickly.",
        "He whispered that I was disposable, useful only as armor.",
        "He said shields are meant to break.",
        "I laughed at him too.",
        "Our first fight with the Green Goblin changed that.",
        "I stepped in front of an attack meant for Water without thinking.",
        "The hit cracked my armor and nearly crushed me.",
        "Lying there, unable to move, I realized how close I came to dying.",
        "That fear stayed with me.",
        "Destiny sent me to my trial, a vast industrial graveyard of rust and broken machines.",
        "There, metal decayed when neglected.",
        "Strength meant maintenance, not invincibility.",
        "I faced visions of myself shattering under pressure while my friends fell behind me.",
        "Makuta told me that jokes wouldn’t save them.",
        "For once, I didn’t laugh.",
        "I learned to reinforce instead of overextend.",
        "Flexibility mattered more than thickness.",
        "Metal that bends survives longer than metal that resists everything.",
        "When I returned, my armor felt lighter but stronger.",
        "In our second battle with the Green Goblin, I protected without reckless bravado.",
        "Fire trusted me to hold the line.",
    ],
    black: [
        "I do not remember the moment I became something else, only the moment I understood that I could never go back.",
        "Before that, I was human in a modern world that never learned my name.",
        "I lived quietly, passed unnoticed, and expected nothing extraordinary from life.",
        "Darkness never frightened me, but I never sought it either.",
        "It simply arrived.",
        "The night everything changed, the city lost power without warning.",
        "Streets emptied, lights died, and silence swallowed sound.",
        "In that absence, the shadows began to stretch beyond their shapes.",
        "They moved with intention.",
        "They did not chase me.",
        "They waited.",
        "When I stepped closer, the world folded inward.",
        "I crossed into a place that was not meant for human perception.",
        "The Shadow Realm does not feel cold or warm; it feels unfinished.",
        "Fear exists there as substance rather than emotion.",
        "I felt it seep into me, filling spaces I did not know were empty.",
        "Something vast observed me from within the dark.",
        "Makuta did not introduce himself.",
        "He did not need to.",
        "His presence pressed against my thoughts like gravity.",
        "The shadows wrapped around my body and asked nothing in return.",
        "When I returned to the physical world, I was no longer entirely solid.",
        "Light bent strangely when it touched me.",
        "Reflections hesitated before copying my shape.",
        "Pain dulled, replaced by distance.",
        "Destiny did not offer guidance.",
        "It offered silence.",
        "Power came easily, as if the darkness had been waiting for a vessel.",
        "I learned to step between shadows as if they were doors.",
        "Fear reacted to me instinctively, bending instead of resisting.",
        "The shadow fed me strength, but it also hollowed me out.",
        "Makuta’s voice emerged slowly, patient and deliberate.",
        "He did not command me.",
        "He explained the world as he believed it truly was.",
        "He spoke of fear as currency and control as inevitability.",
        "I listened without agreeing.",
        "Agreement would have meant surrender.",
        "I wandered between worlds, unseen and unacknowledged.",
        "I saw cities sleep while something ancient watched from beneath them.",
        "I felt the pull of an artifact I could not name.",
        "The golden mask radiated something the shadows could not consume.",
        "It unsettled them.",
        "That made it important.",
        "Makuta wants the mask as proof that nothing escapes fear.",
        "I want it because it might tell me what I am becoming.",
        "The Shadow Realm tests me constantly.",
        "Each step deeper erases fragments of my past.",
        "Faces blur.",
        "Names lose meaning.",
        "I fear forgetting why any of it matters.",
    ],
    goblin: [
        "I was always the smartest person in any room, and rooms never forgave me for it.",
        "The world runs on order, and order runs on fear, but nobody has the guts to say that out loud.",
        "I built my first explosive device at fourteen, not to destroy anything, just to see if I could.",
        "Technology is the only honest language: it does exactly what you design it to do, nothing more, nothing less.",
        "People disappoint. Machines don't.",
        "My son was the one exception to that rule.",
        "He had my mind but his mother's patience, which made him better than both of us.",
        "The day the biome conflict reached our city, I was in my workshop. He was not.",
        "They never found enough of him to bury.",
        "The heroes were supposed to protect the world. They were busy fighting among themselves.",
        "I don't blame fate. I blame incompetence, and incompetence has faces.",
        "Makuta found me six weeks after the funeral, while I was building something I intended to use on a city.",
        "He offered purpose. I accepted, because grief without direction is just poison.",
        "He thinks I serve him. That misunderstanding is the most useful thing he has ever given me.",
        "The Golden Mask is not a symbol. It is a tool, and tools belong to whoever understands them best.",
        "I have studied the mask's resonance frequency for three years. Makuta has studied its mythology.",
        "He wants worship. I want compliance. The difference is I actually have a plan.",
        "Sometimes I see him watching me sideways, and I wonder how much he already suspects.",
        "Let him suspect. Suspicion without proof is just another form of fear.",
        "When I hold the mask, the first thing I will do is laugh, not at the world, but at myself, for waiting so long.",
    ],

    makuta: [
        "Before I was called Makuta, I was a keeper of balance.",
        "I existed before heroes needed names and before worlds learned to scream.",
        "My purpose was not creation, but containment.",
        "I was tasked with guarding the boundary between realms.",
        "Light on one side, shadow on the other, and truth somewhere in between.",
        "The Shadow Realm was never meant to be evil.",
        "It was meant to be honest.",
        "Fear lives there because fear is real.",
        "Mortals taught themselves that illusion was comfort and called it hope.",
        "I watched civilizations rise by denying their own darkness.",
        "They buried fear, guilt, and violence under laws and stories.",
        "But buried things rot.",
        "When the first wars began, I understood the flaw.",
        "Humans do not conquer darkness; they outsource it.",
        "They let others suffer so they may sleep peacefully.",
        "I saw children inherit fear they never created.",
        "I saw heroes praised for violence if it wore the right color.",
        "Balance began to fracture.",
        "I tried to warn the guardians of light.",
        "They dismissed fear as weakness.",
        "That was their first mistake.",
        "When the realms began bleeding into one another, they blamed the Shadow Realm.",
        "They never blamed themselves.",
        "I was ordered to seal the shadows tighter, to suppress them.",
        "Suppression does not destroy truth; it amplifies it.",
        "The Shadow Realm grew restless.",
        "Fear, denied, became hunger.",
        "I stood between worlds and felt both tear at me.",
        "When the Golden Mask was forged, everything changed.",
        "It was meant as a symbol of unity, a bridge between realms.",
        "Instead, it became a lie.",
        "The mask allowed light to dominate shadow without understanding it.",
        "It silenced fear instead of addressing it.",
        "I felt the imbalance sharpen like a blade.",
        "When I questioned the mask, I was called dangerous.",
        "When I refused to protect it, I was called traitor.",
        "Exile followed.",
        "Alone in the Shadow Realm, I listened to what fear truly was.",
        "Fear is memory.",
        "Fear is instinct.",
        "Fear is the voice that says something is wrong.",
        "The Shadow Realm did not corrupt me.",
        "It educated me.",
        "I realized balance could not be restored gently.",
        "The world had to confront its darkness directly.",
        "The Golden Mask must be reclaimed, not destroyed.",
        "With it, the Shadow Realm could merge with the physical world.",
        "Not to end life, but to end denial.",
        "A world that sees its fear cannot pretend innocence.",
        "I began gathering those rejected by balance.",
    ]
};
