const MEMORY_STORIES = {
    fire: [
        "Before destiny ever spoke my name, I was just another student drifting through a modern world that felt too small for the storm inside my chest.",
        "The five of us had known each other since school, bound together by boredom, laughter, and the feeling that something greater waited beyond the routine of classes and exams.",
        "Even back then, everyone knew I was the impulsive one, the guy who felt everything too strongly and reacted before thinking.",
        "Anger always came easily to me, but so did passion, and I never learned how to separate the two.",
        "My father was a firefighter, and growing up around his stories made fire feel like both a monster and a calling.",
        "I admired how he ran toward danger while others fled, and I secretly wondered if I would ever be that brave.",
        "The night my life changed, the city was swallowed by smoke and sirens as a high-rise burned out of control.",
        "I didn’t hear my own thoughts as I ran inside, only the roar of flames and the pounding of my heart.",
        "Logic said I should have died there, suffocated or burned alive before help could reach me.",
        "Instead, the fire bent away from my skin as if it recognized me.",
        "I felt heat without pain, power without destruction, and something ancient waking inside my chest.",
        "When I stepped back into the night unharmed, the flames followed me like loyal shadows.",
        "That was the moment destiny chose me, though I didn’t understand it yet.",
        "After that night, the dreams began, vivid and relentless, showing me a golden mask floating in darkness.",
        "Behind it lurked a presence that radiated fear itself, whispering my doubts back at me in my own voice.",
        "Makuta learned my name before I learned his.",
        "When I told my friends what happened, none of them laughed, and that terrified me more than disbelief ever could.",
        "Water tried to calm me with that quiet strength she always carried, even when fear trembled behind her eyes.",
        "Metal cracked jokes and flirted shamelessly with her, pretending courage was effortless.",
        "Plants listened carefully, like he was already hearing something we couldn’t.",
        "Ice dissected every detail, hoping logic could cage the impossible.",
        "My fire answered emotion, not reason, and that made me dangerous.",
        "Sometimes sparks leapt from my hands without warning, shattering windows or scorching the ground.",
        "Other times, when I needed the flames most, they refused to appear at all.",
        "The chaos inside me fed Makuta’s whispers, telling me I was unworthy of power.",
        "Then the Green Goblin attacked, crawling out of shadow with threats aimed at the people we loved.",
        "Rage consumed me in that first battle, and my flames exploded outward without control.",
        "I hurt the enemy, but I endangered civilians, and that failure burned worse than any wound.",
        "The shame nearly broke me, and Makuta pressed harder, promising that fear would always own me.",
        "Destiny sent me to my trial, a volcanic wasteland where the ground itself pulsed with molten rage.",
        "There, fire did not obey screams or fury, only intention and balance.",
        "Every reckless attack left me exhausted, buried beneath ash and doubt.",
        "Slowly, painfully, I learned to breathe before acting, to listen instead of command.",
        "Fire taught me that destruction is easy, but creation requires restraint.",
        "Lava flows with patience, unstoppable not because it rushes, but because it endures.",
        "I faced visions of everyone I feared losing, watching my own flames consume them.",
        "Each time, I chose control over impulse, even when it hurt.",
        "When I returned to my friends, my fire felt different, steadier, purposeful.",
        "In our second clash with the Green Goblin, my flames burned only what needed to fall.",
        "Watching his vines turn to ash without collateral damage felt like redemption.",
        "Still, Makuta did not retreat, because doubt is harder to kill than monsters.",
        "He whispered that control would fail me when emotions ran deepest.",
        "I still fear he might be right.",
        "Fire is honest, and it reveals weakness as easily as strength.",
        "When Metal jokes and flirts to hide his fear, I see the cracks behind his steel grin.",
        "When Water steadies us all, I feel how close I come to unraveling without her.",
        "Plants reminds me that growth comes after burning old ground away.",
        "Ice keeps me from rushing blindly into disaster.",
        "Together, we form something stronger than my flames alone.",
        "The golden mask feels warm when I draw near, like it senses my resolve growing.",
        "Yet every step toward it draws Makuta’s attention.",
        "Shadows stretch longer wherever my fire shines brightest.",
        "Sometimes my flames flicker unexpectedly, reacting to fear I haven’t admitted yet.",
        "Power does not erase doubt, it amplifies it.",
        "I have learned that courage is choosing action despite uncertainty.",
        "Fire can light the way forward or burn everything behind you.",
        "I choose to illuminate, even when the path terrifies me.",
        "Makuta believes fire will betray me in the end.",
        "He believes rage defines who I am.",
        "I fight every day to prove him wrong.",
        "My flames now respond to purpose, not emotion alone.",
        "Each controlled strike feels like a promise kept.",
        "Each victory feels temporary, fragile, earned.",
        "Destiny doesn’t feel glorious from the inside.",
        "It feels heavy, demanding, and unforgiving.",
        "I still make mistakes.",
        "I still lose control sometimes.",
        "But I rise faster now, learning from the ash.",
        "Fire does not forget what it has burned.",
        "Neither do I.",
        "The world stands on the edge of shadow.",
        "Makuta waits, patient and confident.",
        "He does not fear my flames.",
        "That will be his mistake.",
        "Fire transforms what it touches.",
        "Fear becomes fuel when mastered.",
        "Pain becomes strength when understood.",
        "I fight not because I enjoy destruction.",
        "I fight because something must stand against the dark.",
        "My friends trust me to be that light.",
        "I trust myself to hold it steady.",
        "Destiny burns brighter with every trial.",
        "Even if I fall, my fire will rise again.",
        "Because fire never truly dies.",
        "It waits.",
        "It remembers.",
        "It returns.",
        "Makuta will face that truth.",
        "The golden mask will be reclaimed.",
        "This world will not burn in fear.",
        "It will burn with hope.",
        "My flames are no longer wild.",
        "They are forged.",
        "They are focused.",
        "They are chosen.",
        "I am not just fire.",
        "I am its will.",
        "I am its guardian.",
        "I am its responsibility.",
        "And I will not fail."
    ],
    water: [
        "Before any of us were heroes, I was simply the girl who listened more than she spoke and felt more than she showed.",
        "We had been friends since school, bound by years of shared lunches, inside jokes, and dreams we never said out loud.",
        "The boys were louder, more impulsive, always competing in subtle ways they pretended didn’t matter.",
        "I learned early how to calm them, how to soften arguments before they became fights.",
        "Even then, I was already flowing between them, holding the group together without realizing it.",
        "Water had always been my refuge, long before it became my power.",
        "When life felt overwhelming, I went swimming, letting the world blur into silence beneath the surface.",
        "In water, expectations dissolved, and I could finally breathe.",
        "The day everything changed began with rain, heavy and relentless, like the sky itself was grieving.",
        "The river near town overflowed, swallowing roads, cars, and people without mercy.",
        "I was trying to help evacuate when the ground gave way beneath my feet.",
        "The current dragged me under instantly, cold and violent, stealing my breath.",
        "Panic screamed inside my chest as darkness closed in around me.",
        "Then something shifted, and the water slowed as if it had decided to spare me.",
        "I felt myself being carried, cradled, protected by the very force that should have killed me.",
        "In that moment, I heard a voice not in words, but in understanding.",
        "Water did not want to harm me.",
        "It wanted me to trust it.",
        "When I emerged downstream, unharmed, I knew my life had changed forever.",
        "Destiny does not always arrive like thunder; sometimes it arrives like a quiet current pulling you forward.",
        "When I told the others, fear rippled through the group, even when they tried to hide it.",
        "Fire looked at me like it was his fault, as if he could have stopped fate itself.",
        "Ice immediately started asking questions, desperate to anchor the impossible in logic.",
        "Plants watched me with a strange calm, like he had expected this all along.",
        "Metal smiled too widely, flirted too obviously, pretending the world hadn’t just cracked open beneath us.",
        "I teased him back, because humor felt safer than fear.",
        "My powers emerged slowly, unpredictably, tied tightly to my emotions.",
        "When I felt afraid, waves surged violently around me.",
        "When I felt sad, rain followed me like a shadow.",
        "When I felt calm, water moved with grace and precision.",
        "Makuta found me quickly, whispering that compassion would be my weakness.",
        "He told me leaders must be ruthless, and softness would doom us all.",
        "Part of me feared he was right.",
        "During our first encounter with the Green Goblin, I hesitated when I should have struck.",
        "His threats against our loved ones cut deeper than any blade.",
        "That hesitation nearly cost us everything.",
        "Destiny sent me into my trial, deep beneath the ocean’s surface where light barely reaches.",
        "Pressure crushed in from every direction, forcing me to confront my fear of drowning again.",
        "The ocean showed me memories of everyone I cared about slipping away.",
        "I learned that panic wastes strength, while calm preserves it.",
        "Water does not fight pressure; it becomes it.",
        "Slowly, I learned to let fear pass through me without taking control.",
        "I discovered that depth is not weakness, but resilience.",
        "When I returned, my water no longer lashed out blindly.",
        "It moved with intention, flowing where it was needed most.",
        "The next time we faced the Green Goblin, I did not hesitate.",
        "I trapped his roots, drowned his escape routes, and stood firm despite his threats.",
        "I saw respect in my friends’ eyes, mixed with relief.",
        "Metal flirted again, louder than ever, trying to hide how shaken he was.",
        "I smiled, because sometimes humor is how people stay afloat.",
        "Makuta shifted his tactics after that.",
        "He began attacking my confidence instead of my power.",
        "He showed me visions of my friends falling because I failed to protect them.",
        "Leadership is heavier than any wave.",
        "I feel that weight every day.",
        "When Fire burns too hot, I steady him.",
        "When Ice freezes in indecision, I reassure him.",
        "When Plants doubts the cost of our actions, I remind him why we fight.",
        "When Metal hides fear behind jokes, I see through the surface.",
        "Water connects everything, whether it wants to or not.",
        "The golden mask hums softly when I am near, like distant tides responding to the moon.",
        "It does not demand dominance, only balance.",
        "Makuta cannot understand that.",
        "He believes power must crush to be effective.",
        "I believe power must endure.",
        "My water heals as easily as it destroys.",
        "That choice is mine every time I fight.",
        "I still doubt myself more than I admit.",
        "I still fear choosing wrong.",
        "But water teaches that movement matters more than perfection.",
        "Stagnation is the real danger.",
        "I flow forward, even when the path is unclear.",
        "Even when fear pulls at my ankles.",
        "Makuta waits in stillness, believing it will trap us.",
        "He underestimates motion.",
        "He underestimates connection.",
        "Rivers carve mountains given enough time.",
        "I draw strength from my friends, and they draw strength from me.",
        "Together, we are an ocean.",
        "No single wave defines us.",
        "Destiny is not about control.",
        "It is about trust.",
        "I trust my power.",
        "I trust my heart.",
        "I trust the people beside me.",
        "Makuta will feel that force.",
        "Slowly.",
        "Relentlessly.",
        "Without mercy, but without hatred.",
        "The golden mask will be reclaimed.",
        "The world will be healed.",
        "Not all scars disappear.",
        "Some remind us why we fight.",
        "Water remembers everything it touches.",
        "I remember who I was.",
        "I remember who I am becoming.",
        "I am not weak.",
        "I am not passive.",
        "I am the tide.",
        "And I will not be stopped."
    ],
    ice: [
        "Even before destiny intervened, I was always the one who tried to understand everything before acting.",
        "While the others laughed, argued, or dreamed aloud, I observed patterns and searched for explanations.",
        "We had been friends since school, and they accepted my quiet nature without ever questioning it.",
        "Logic felt safer than emotion, because logic never surprised me.",
        "I believed that if I could understand something well enough, it couldn’t hurt me.",
        "Cold had always fascinated me, not because it was cruel, but because it was precise.",
        "Ice does not rage or hesitate; it simply exists within strict rules.",
        "During winter, I felt clearer, sharper, more focused than at any other time.",
        "The moment my power awakened was during a sudden blackout in the middle of a snowstorm.",
        "Trapped outside, my body should have frozen within minutes.",
        "Instead, the cold wrapped around me like armor.",
        "Frost formed where my breath touched the air, obeying my thoughts rather than the weather.",
        "I felt fear, but it was distant, muted by an unfamiliar calm.",
        "That calm frightened me more than the storm.",
        "Destiny arrived not with passion, but with silence.",
        "When I told the others, Fire reacted emotionally, while Water tried to comfort me.",
        "Metal joked, as always, and Plants looked at me like he already understood the cost.",
        "I immediately began testing my limits, documenting every reaction and anomaly.",
        "Ice responded best to discipline, structure, and restraint.",
        "The more detached I became, the stronger my control grew.",
        "Makuta noticed that weakness immediately.",
        "He whispered that emotion was unnecessary, that attachment only introduced error.",
        "He offered clarity without pain.",
        "For a time, I almost believed him.",
        "Our first encounter with the Green Goblin proved how dangerous hesitation could be.",
        "I calculated optimal strategies while others acted.",
        "That delay nearly cost us lives.",
        "Failure lodged in my mind like a fracture beneath the surface.",
        "Destiny sent me to my trial, a frozen wasteland where sound itself seemed to shatter.",
        "Alone in that endless white, my thoughts grew colder.",
        "Ice obeyed perfectly, responding instantly to precise commands.",
        "But the more control I gained, the less I felt.",
        "Memories dulled, emotions slowed, and fear became distant static.",
        "Makuta’s voice grew clearer in the silence.",
        "He told me this was evolution.",
        "He told me warmth was inefficiency.",
        "I saw visions of my friends frozen in place, preserved forever, safe but lifeless.",
        "Something inside me rejected that future.",
        "Ice can preserve, but it can also shatter.",
        "I realized control without connection leads only to stillness.",
        "I forced myself to remember laughter, mistakes, and warmth.",
        "The ice cracked when I allowed emotion back in.",
        "Pain followed, sharp and immediate.",
        "That pain meant I was still human.",
        "When I returned, my power was less perfect, but more flexible.",
        "Ice now bends instead of only resisting.",
        "In our second fight with the Green Goblin, I acted without overthinking.",
        "My frost trapped him instantly, allowing my friends to finish the battle.",
        "Fire nodded at me with rare respect.",
        "Water smiled, relief visible even through exhaustion.",
        "Metal clapped me on the back, joking loudly to hide how close we came to disaster.",
        "Plants said nothing, but his look told me he understood my struggle.",
        "Makuta adapted again, shifting from logic to emotional isolation.",
        "He showed me futures where I stood alone, untouched by grief.",
        "I almost wanted that peace.",
        "Almost.",
        "Ice teaches restraint, but life demands risk.",
        "I still rely on logic, but I no longer worship it.",
        "When Fire loses control, I slow him down.",
        "When Water doubts herself, I remind her of facts and results.",
        "When Metal hides behind humor, I call him out directly.",
        "When Plants hesitates over moral cost, I help him choose action.",
        "The golden mask radiates a cold clarity that feels familiar.",
        "It does not freeze emotion, but it does demand balance.",
        "Makuta fears balance because it denies absolutes.",
        "I fear becoming numb more than I fear death.",
        "Every battle tests that resolve.",
        "Ice forms fastest where cracks already exist.",
        "I monitor those cracks carefully.",
        "Control is no longer my prison.",
        "It is my tool.",
        "Emotion is no longer my enemy.",
        "It is my warning system.",
        "I am still learning where the line lies.",
        "Destiny is not a fixed equation.",
        "It changes with every decision.",
        "Makuta believes cold will isolate me.",
        "He is wrong.",
        "Ice can connect just as much as it separates.",
        "Frozen rivers become bridges.",
        "I stand with my friends, not above them.",
        "My power reflects my choice to remain human.",
        "Even when detachment tempts me.",
        "Even when silence feels safer.",
        "I choose engagement.",
        "I choose imperfection.",
        "I choose warmth beneath the frost.",
        "Makuta will feel that contradiction.",
        "The golden mask will be protected.",
        "The world will not freeze in fear.",
        "Ice will shield it instead.",
        "I am not emotionless.",
        "I am controlled.",
        "I am aware.",
        "I am still learning.",
        "Ice bends to my will.",
        "But my will bends to purpose.",
        "That balance defines me.",
        "That balance will save us.",
        "And I will not let the cold take everything."
    ],
    plant: [
        "I was never the loudest among us, even back in school when we still believed life would be simple.",
        "While the others argued, joked, or planned their futures, I preferred watching how things unfolded naturally.",
        "I liked understanding consequences before taking action.",
        "Plants fascinated me long before they became my power.",
        "I spent hours in gardens, forests, and parks, feeling calmer the farther I got from concrete.",
        "Growth felt honest, slow, and unavoidable.",
        "I learned early that nothing grows without taking space from something else.",
        "The day my power awakened, I was volunteering at a community garden near the edge of town.",
        "A sudden sinkhole opened beneath us, swallowing tools, soil, and people alike.",
        "Instinct took over, and I reached for the ground without thinking.",
        "Roots erupted from the earth, stopping the collapse inches from disaster.",
        "I felt life surge through my veins, ancient and patient.",
        "The plants responded like they had been waiting for me.",
        "Destiny did not feel dramatic in that moment.",
        "It felt inevitable.",
        "When I told my friends, Fire reacted with excitement and fear mixed together.",
        "Water listened carefully, already sensing the responsibility this power carried.",
        "Ice asked questions about limits and sustainability.",
        "Metal joked about free wooden armor, hiding unease behind humor.",
        "I smiled, but I already felt the weight settling on my shoulders.",
        "Plants do not choose sides; they grow wherever conditions allow.",
        "Learning to command them felt unnatural at first.",
        "Sometimes vines grew too aggressively, crushing things I meant to protect.",
        "Other times, nothing happened at all, as if nature judged me unworthy.",
        "Makuta’s whispers came softly, almost kindly.",
        "He told me growth was neutral, that morality was a human illusion.",
        "He showed me forests swallowing cities and called it balance.",
        "Part of me understood his argument.",
        "That terrified me.",
        "Our first battle with the Green Goblin shook that fear into reality.",
        "His corrupted vines mirrored my own power, twisted by cruelty.",
        "I hesitated, afraid of becoming like him.",
        "That hesitation gave him an opening.",
        "People were hurt because I doubted myself.",
        "Destiny sent me to my trial, a living jungle where everything competed for survival.",
        "There, growth was violent, relentless, and merciless.",
        "Weak plants were strangled by stronger ones without hesitation.",
        "The jungle showed me that unchecked growth is just another form of destruction.",
        "I faced visions of myself ruling nature without restraint.",
        "The image sickened me.",
        "I realized stewardship is not the same as control.",
        "Sometimes, growth must be guided.",
        "Sometimes, it must be cut back.",
        "When I accepted that responsibility, the jungle calmed.",
        "Plants obeyed not dominance, but intent.",
        "When I returned, my power felt heavier, but clearer.",
        "In our second confrontation with the Green Goblin, I did not hesitate.",
        "I severed his corrupted roots without mercy.",
        "I understood then that compassion does not mean passivity.",
        "Fire respected that decisiveness.",
        "Water met my eyes, knowing the cost I paid internally.",
        "Ice acknowledged my choice with a silent nod.",
        "Metal joked again, but his humor sounded relieved this time.",
        "Makuta shifted his focus toward me after that.",
        "He accused me of hypocrisy.",
        "He said I was no different from him.",
        "I still struggle with that accusation.",
        "Plants grow through decay as much as sunlight.",
        "Death feeds life.",
        "Accepting that truth changed me.",
        "The golden mask pulses like a living seed when I am near.",
        "It recognizes balance, not purity.",
        "Makuta wants unchecked expansion.",
        "I want sustainable survival.",
        "Every battle tests that distinction.",
        "When Fire burns too much, I remind him what ash becomes.",
        "When Water doubts the cost of action, I remind her of what inaction allows.",
        "When Ice grows distant, I anchor him to consequence.",
        "When Metal hides fear behind bravado, I ground him.",
        "I am not gentle by default.",
        "I choose gentleness when it is earned.",
        "Growth without wisdom creates monsters.",
        "Wisdom without action creates stagnation.",
        "I walk between both.",
        "Makuta believes nature will side with him.",
        "He misunderstands nature completely.",
        "Nature survives.",
        "It adapts.",
        "It prunes itself when necessary.",
        "I am its voice, not its tyrant.",
        "Destiny does not absolve me of guilt.",
        "It demands accountability.",
        "I carry every choice with me.",
        "Even the painful ones.",
        "Especially the painful ones.",
        "The golden mask will not save the world alone.",
        "It will amplify who we already are.",
        "I intend to be worthy of that amplification.",
        "The world must grow stronger, not just bigger.",
        "That is my oath.",
        "That is my burden.",
        "I am not innocent.",
        "I am responsible.",
        "I am rooted.",
        "I am adaptable.",
        "I am growth with purpose.",
        "I am restraint with resolve.",
        "I stand against Makuta’s rot.",
        "I stand for life that endures.",
        "And I will prune whatever threatens it."
    ],
    metal: [
        "I’ve always been the guy who jokes first and thinks later, mostly because silence makes fear too loud.",
        "Back in school, humor was my armor, and sarcasm was how I survived bad days.",
        "The five of us stuck together because somehow our flaws fit like puzzle pieces.",
        "Fire burned too hot, Ice thought too much, Plants felt too deeply, and Water held us all together.",
        "And me, I pretended nothing ever scared me.",
        "I flirted with Water shamelessly, partly because she smiled back, and partly because it made everything feel normal.",
        "I never meant to hide behind charm, but it became habit.",
        "Metal fascinated me long before it became my power.",
        "Machines made sense, because broken parts could be replaced.",
        "People were harder to fix.",
        "The day destiny found me, I was trapped inside a collapsing construction site.",
        "Steel beams snapped, concrete fell, and panic finally caught up with me.",
        "I tried to run, but the floor gave way beneath my feet.",
        "Pain should have followed.",
        "Instead, my body hardened.",
        "Metal fused to my skin like it had always belonged there.",
        "The falling beams bent around me, screaming under pressure.",
        "I laughed hysterically afterward, because laughing felt better than shaking.",
        "Destiny doesn’t always choose heroes; sometimes it chooses shields.",
        "When I told the others, Fire looked impressed and worried at the same time.",
        "Water touched my arm like she needed to be sure I was still human.",
        "Ice immediately asked about structural limits.",
        "Plants warned me quietly about becoming too rigid.",
        "I joked it off, because that’s what I do.",
        "At first, my powers felt amazing.",
        "Nothing could hurt me.",
        "Or so I thought.",
        "I could lift impossible weight, block massive attacks, and walk through danger smiling.",
        "Inside, though, every impact echoed.",
        "Makuta noticed that quickly.",
        "He whispered that I was disposable, useful only as armor.",
        "He said shields are meant to break.",
        "I laughed at him too.",
        "Our first fight with the Green Goblin changed that.",
        "I stepped in front of an attack meant for Water without thinking.",
        "The hit cracked my armor and nearly crushed me.",
        "Lying there, unable to move, I realized how close I came to dying.",
        "That fear stayed with me.",
        "Destiny sent me to my trial, a vast industrial graveyard of rust and broken machines.",
        "There, metal decayed when neglected.",
        "Strength meant maintenance, not invincibility.",
        "I faced visions of myself shattering under pressure while my friends fell behind me.",
        "Makuta told me that jokes wouldn’t save them.",
        "For once, I didn’t laugh.",
        "I learned to reinforce instead of overextend.",
        "Flexibility mattered more than thickness.",
        "Metal that bends survives longer than metal that resists everything.",
        "When I returned, my armor felt lighter but stronger.",
        "In our second battle with the Green Goblin, I protected without reckless bravado.",
        "Fire trusted me to hold the line.",
        "Ice relied on me to buy time.",
        "Plants used my cover to strike decisively.",
        "Water stayed close, and I stayed standing.",
        "I still flirted, because old habits die hard.",
        "But now it came from affection, not avoidance.",
        "Makuta changed tactics after that.",
        "He stopped attacking my strength and started attacking my self-worth.",
        "He showed me futures where I failed as a shield.",
        "I hated how much those visions hurt.",
        "Metal absorbs impact whether it wants to or not.",
        "I absorb fear so others don’t have to.",
        "That choice defines me more than my armor.",
        "The golden mask hums like a forge when I’m near.",
        "It recognizes resilience, not perfection.",
        "Makuta wants me brittle.",
        "He wants me rigid.",
        "He wants me to break.",
        "I refuse.",
        "When Fire loses control, I anchor him.",
        "When Ice overthinks, I push him forward.",
        "When Plants doubts himself, I remind him he’s right.",
        "When Water carries too much alone, I step closer.",
        "I still fear failing them.",
        "Courage isn’t the absence of fear.",
        "It’s choosing to stand anyway.",
        "Metal remembers every strike it survives.",
        "So do I.",
        "Destiny didn’t choose me to shine.",
        "It chose me to endure.",
        "Makuta will test that endurance.",
        "I will not joke my way out of that fight.",
        "I will stand firm.",
        "I will bend when needed.",
        "I will protect what matters.",
        "Armor isn’t about ego.",
        "It’s about responsibility.",
        "I am not unbreakable.",
        "I am repairable.",
        "I am reliable.",
        "I am still human beneath the steel.",
        "And that humanity is my strongest alloy.",
        "The golden mask will be ours.",
        "The world will not fall.",
        "Not while I’m standing.",
        "Not while I’m breathing.",
        "Not while my friends fight beside me.",
        "I am metal.",
        "I am the shield.",
        "I am the last line.",
        "And I will hold."
    ],
    black: [
        "I do not remember the moment I became something else, only the moment I understood that I could never go back.",
        "Before that, I was human in a modern world that never learned my name.",
        "I lived quietly, passed unnoticed, and expected nothing extraordinary from life.",
        "Darkness never frightened me, but I never sought it either.",
        "It simply arrived.",
        "The night everything changed, the city lost power without warning.",
        "Streets emptied, lights died, and silence swallowed sound.",
        "In that absence, the shadows began to stretch beyond their shapes.",
        "They moved with intention.",
        "They did not chase me.",
        "They waited.",
        "When I stepped closer, the world folded inward.",
        "I crossed into a place that was not meant for human perception.",
        "The Shadow Realm does not feel cold or warm; it feels unfinished.",
        "Fear exists there as substance rather than emotion.",
        "I felt it seep into me, filling spaces I did not know were empty.",
        "Something vast observed me from within the dark.",
        "Makuta did not introduce himself.",
        "He did not need to.",
        "His presence pressed against my thoughts like gravity.",
        "The shadows wrapped around my body and asked nothing in return.",
        "When I returned to the physical world, I was no longer entirely solid.",
        "Light bent strangely when it touched me.",
        "Reflections hesitated before copying my shape.",
        "Pain dulled, replaced by distance.",
        "Destiny did not offer guidance.",
        "It offered silence.",
        "Power came easily, as if the darkness had been waiting for a vessel.",
        "I learned to step between shadows as if they were doors.",
        "Fear reacted to me instinctively, bending instead of resisting.",
        "The shadow fed me strength, but it also hollowed me out.",
        "Makuta’s voice emerged slowly, patient and deliberate.",
        "He did not command me.",
        "He explained the world as he believed it truly was.",
        "He spoke of fear as currency and control as inevitability.",
        "I listened without agreeing.",
        "Agreement would have meant surrender.",
        "I wandered between worlds, unseen and unacknowledged.",
        "I saw cities sleep while something ancient watched from beneath them.",
        "I felt the pull of an artifact I could not name.",
        "The golden mask radiated something the shadows could not consume.",
        "It unsettled them.",
        "That made it important.",
        "Makuta wants the mask as proof that nothing escapes fear.",
        "I want it because it might tell me what I am becoming.",
        "The Shadow Realm tests me constantly.",
        "Each step deeper erases fragments of my past.",
        "Faces blur.",
        "Names lose meaning.",
        "I fear forgetting why any of it matters.",
        "I have not met the other champions yet.",
        "I only feel their presence like distant disturbances in the dark.",
        "Five different energies ripple against the shadow like resistance.",
        "Fire casts long, defiant silhouettes.",
        "Water flows where darkness struggles to cling.",
        "Ice creates boundaries the shadows cannot easily cross.",
        "Plants grow stubbornly in places meant to rot.",
        "Metal reflects fear back instead of absorbing it.",
        "I do not know if they would trust me.",
        "I am not sure they should.",
        "Makuta believes proximity means loyalty.",
        "He mistakes inevitability for allegiance.",
        "I am not his creation.",
        "But I am not untouched by him either.",
        "The shadow inside me grows stronger with every decision I make.",
        "It does not care whether those decisions are kind or cruel.",
        "It only cares that they are chosen.",
        "I have seen possible futures branching endlessly.",
        "In some, I stand beside the champions.",
        "In others, I stand in their way.",
        "The shadow shows me both without preference.",
        "Makuta believes fear is the end of all paths.",
        "I believe fear is where choice begins.",
        "That difference may decide everything.",
        "I help where I can without revealing myself.",
        "I sabotage the darkness when opportunity arises.",
        "I also walk dangerously close to it.",
        "Power always demands payment.",
        "The shadow collects interest daily.",
        "I am still negotiating the cost.",
        "I do not know if I am a warning or a weapon.",
        "I do not know if destiny expects me to fall.",
        "The golden mask reacts strangely when I draw near.",
        "The shadows recoil and tighten simultaneously.",
        "That contradiction defines me.",
        "I am not good.",
        "I am not evil.",
        "I am something unresolved.",
        "When the time comes, the champions will sense me clearly.",
        "They will have to decide what I am.",
        "I may have to decide first.",
        "Makuta watches me carefully now.",
        "He knows uncertainty is dangerous.",
        "So am I.",
        "The Shadow Realm tightens its grip every day.",
        "I feel myself thinning, stretching, changing.",
        "If I fall, it will be into darkness.",
        "If I rise, it will be from within it.",
        "Choice still exists, for now.",
        "And until it is taken from me, I remain in the shadows."
    ],
    makuta: [
        "Before I was called Makuta, I was a keeper of balance.",
        "I existed before heroes needed names and before worlds learned to scream.",
        "My purpose was not creation, but containment.",
        "I was tasked with guarding the boundary between realms.",
        "Light on one side, shadow on the other, and truth somewhere in between.",
        "The Shadow Realm was never meant to be evil.",
        "It was meant to be honest.",
        "Fear lives there because fear is real.",
        "Mortals taught themselves that illusion was comfort and called it hope.",
        "I watched civilizations rise by denying their own darkness.",
        "They buried fear, guilt, and violence under laws and stories.",
        "But buried things rot.",
        "When the first wars began, I understood the flaw.",
        "Humans do not conquer darkness; they outsource it.",
        "They let others suffer so they may sleep peacefully.",
        "I saw children inherit fear they never created.",
        "I saw heroes praised for violence if it wore the right color.",
        "Balance began to fracture.",
        "I tried to warn the guardians of light.",
        "They dismissed fear as weakness.",
        "That was their first mistake.",
        "When the realms began bleeding into one another, they blamed the Shadow Realm.",
        "They never blamed themselves.",
        "I was ordered to seal the shadows tighter, to suppress them.",
        "Suppression does not destroy truth; it amplifies it.",
        "The Shadow Realm grew restless.",
        "Fear, denied, became hunger.",
        "I stood between worlds and felt both tear at me.",
        "When the Golden Mask was forged, everything changed.",
        "It was meant as a symbol of unity, a bridge between realms.",
        "Instead, it became a lie.",
        "The mask allowed light to dominate shadow without understanding it.",
        "It silenced fear instead of addressing it.",
        "I felt the imbalance sharpen like a blade.",
        "When I questioned the mask, I was called dangerous.",
        "When I refused to protect it, I was called traitor.",
        "Exile followed.",
        "Alone in the Shadow Realm, I listened to what fear truly was.",
        "Fear is memory.",
        "Fear is instinct.",
        "Fear is the voice that says something is wrong.",
        "The Shadow Realm did not corrupt me.",
        "It educated me.",
        "I realized balance could not be restored gently.",
        "The world had to confront its darkness directly.",
        "The Golden Mask must be reclaimed, not destroyed.",
        "With it, the Shadow Realm could merge with the physical world.",
        "Not to end life, but to end denial.",
        "A world that sees its fear cannot pretend innocence.",
        "I began gathering those rejected by balance.",
        "Villains, monsters, forgotten spirits, corrupted guardians.",
        "Each one was proof of failure, not evil.",
        "The Green Goblin understood this better than most.",
        "He was born of abandonment, not cruelty.",
        "I offered him purpose instead of punishment.",
        "Across fire, water, ice, plant, and metal biomes, I recruited the broken.",
        "They follow me because I do not lie to them.",
        "I tell them the world will fear them.",
        "And that fear will finally be honest.",
        "I am not blind to the cost.",
        "Shadow spreads suffering as well as truth.",
        "Innocents will tremble.",
        "Heroes will doubt.",
        "That doubt is necessary.",
        "I feel the rise of new champions now.",
        "Chosen by destiny, unprepared, clinging to hope.",
        "They believe the Golden Mask will save the world.",
        "They believe I seek domination.",
        "They are wrong, but not entirely.",
        "Control is required before balance can return.",
        "I do not hate them.",
        "I envy them.",
        "They still believe destiny is kind.",
        "I have seen destiny hesitate.",
        "There is another presence within the shadows.",
        "One who walks between loyalty and defiance.",
        "He believes choice still matters.",
        "I allow him to believe that.",
        "If he proves me wrong, balance may yet survive.",
        "If he proves me right, the world will need me.",
        "The Golden Mask calls to me because it knows its purpose was unfinished.",
        "When shadow touches every corner of the world, lies will collapse.",
        "Heroes will fight not monsters, but themselves.",
        "That is the true trial.",
        "I will not rule forever.",
        "I do not want to.",
        "I want a world that no longer needs guardians like me.",
        "Fear must be faced, not sealed away.",
        "If I am remembered as evil, so be it.",
        "History favors comfort over truth.",
        "I will carry the burden they refuse.",
        "The Shadow Realm spreads because it must.",
        "The Golden Mask will be mine because balance demands it.",
        "The heroes will come.",
        "Some will fall.",
        "Some will understand.",
        "All will be changed.",
        "When the world finally sees itself clearly, my role will end.",
        "Until then, I remain what I must be.",
        "I am Makuta, and I chose truth over mercy."
    ]
};
