const MEMORY_STORIES = {
    fire: [
        "I remember the first time I felt the heat. Not from the sun, but from within.",
        "My village was cold, always cold. The winters were long and unforgiving.",
        "I was just a boy, trying to keep the hearth burning for my mother.",
        "She was sick. The cold was taking her, slowly, day by day.",
        "I prayed for warmth. I prayed for fire. I didn't know what I was asking for.",
        "One night, the wood ran out. The fire died. The cold crept in.",
        "I held her hand. It was like ice. I squeezed it, willing my own warmth into her.",
        "Then it happened. A spark, right there in my palm.",
        "It didn't burn me. It felt... right. Like a heartbeat.",
        "The spark grew. It danced across my fingers, a living thing.",
        "I touched the cold logs. They ignited instantly. The room filled with light.",
        "My mother opened her eyes. She smiled. She felt it too.",
        "But the fire didn't stop. It wanted more. It was hungry.",
        "I ran outside, into the snow. I was afraid I would burn the house down.",
        "The snow melted around me. Steam rose in great clouds.",
        "The village elders saw me. They saw the flames licking at my skin.",
        "They called it a curse. A demon's touch.",
        "I didn't care. I was warm. For the first time, I was truly warm.",
        "They drove me out. Fear makes people do terrible things.",
        "I wandered the mountains. The cold could not touch me.",
        "I learned to control it. To feed it only what I chose.",
        "I realized the fire wasn't a curse. It was a gift. A responsibility.",
        "I met others. Outcasts, like me. But different.",
        "One was made of water. We should have been enemies.",
        "But he laughed when my fire hissed against his skin.",
        "He taught me that fire needs air to breathe, but water gives it shape.",
        "We are not so different. We are all energy, just in different forms.",
        "I fight now to protect those who cannot protect themselves.",
        "The darkness is cold. It reminds me of those long winters.",
        "I will burn it away. I will be the sun for this world.",
        "Sometimes, I miss the quiet of the snow. The silence before the flame.",
        "But silence is close to death. Fire is life. Fire is action.",
        "My anger is a fuel. I must be careful not to let it consume me.",
        "I remember the look in my mother's eyes. It wasn't fear. It was wonder.",
        "That is what I hold onto. The wonder of the light.",
        "The others look to me for strength. I cannot let them down.",
        "I am the vanguard. The first strike. The blazing path.",
        "But even a fire needs to rest. To smolder.",
        "I sit by the campfire and watch the embers. They tell stories.",
        "Stories of a time before the Void. Before the monsters.",
        "I wonder if I can ever go back. To be just a man.",
        "No. The fire has changed me. I am forged anew.",
        "I am not just a man anymore. I am the Flame.",
        "I see the fear in the enemy's eyes. Good. Let them fear.",
        "They bring only cold and shadow. I bring the dawn.",
        "My friends... they are my fuel now. My reason to burn.",
        "Water cools my temper. Earth grounds me. Air feeds my spirit.",
        "Metal... Metal is strange. He is hard, unyielding. But he conducts my heat.",
        "We are a team. A family. Forged in battle.",
        "I will not let the darkness take them. Not while I have a spark left.",
        "The Void whispers to me. It promises power. Unlimited fuel.",
        "But it is a cold fire. A fire that consumes the soul.",
        "I reject it. My fire is my own. It comes from the heart.",
        "I remember the taste of ash. The smell of smoke.",
        "It is the scent of survival. Of victory.",
        "Every battle leaves a mark. A scar. I wear them proudly.",
        "They are the map of my life. The history of my burning.",
        "I dream of a world where fire is only for warmth. Not for war.",
        "A world where children don't have to pray for heat.",
        "Until then, I will be their shield of flame.",
        "I will stand between the innocent and the dark.",
        "Let them come. I am ready. I am burning.",
        "The heat inside me is growing. I feel it evolving.",
        "It is not just red anymore. It is blue. White. Pure energy.",
        "I am becoming something else. Something more.",
        "Is this what it means to be a hero? To lose yourself in the power?",
        "No. I must remember who I am. The boy in the snow.",
        "The boy who just wanted to save his mother.",
        "That love is the core of the flame. The hottest part.",
        "Without it, I am just destruction. With it, I am salvation.",
        "I look at the stars. They are fires too. Distant kin.",
        "One day, I will join them. I will burn in the sky.",
        "But not yet. There is work to do here.",
        "The shadows are lengthening. The night is coming.",
        "Let it come. I shine brightest in the dark.",
        "My sword is flame. My will is iron. My heart is fire.",
        "I am the Phoenix. I rise from the ashes.",
        "Every defeat is just a chance to ignite again.",
        "I will not burn out. I will not fade.",
        "I am the eternal flame. The keeper of the light.",
        "Remember me not for the destruction, but for the warmth.",
        "Remember that even in the coldest winter, there is hope.",
        "Hope is a spark. Nurture it.",
        "Feed it. Let it grow.",
        "And when the time comes, let it roar.",
        "I am Fire. And I am free.",
        "The past is ash. The future is fuel.",
        "I burn for the now.",
        "For this moment.",
        "For us.",
        "Together, we are an inferno.",
        "Unstoppable.",
        "Brilliant.",
        "Alive.",
        "This is my story. Written in flame.",
        "And it is not over yet."
    ],
    water: [
        "The ocean has no beginning and no end. It just is.",
        "I was born on an island. The sea was my cradle.",
        "I learned to swim before I could walk.",
        "The water spoke to me. In whispers. In roars.",
        "It told me of the deep places. The secrets hidden below.",
        "I was a fisherman. A simple life. A good life.",
        "But the sea called me. It pulled at my soul like the tide.",
        "One day, a storm came. A storm unlike any other.",
        "The waves were black. The sky was green.",
        "My boat was crushed. I sank into the abyss.",
        "I thought I would die. I accepted it. I embraced the water.",
        "But I didn't drown. I breathed.",
        "The water filled my lungs, but it gave me life, not death.",
        "I opened my eyes. I saw the city beneath the waves.",
        "Not a city of stone, but of light and coral.",
        "The spirits of the ocean gathered around me.",
        "They told me I was chosen. A vessel for the Tides.",
        "I surfaced days later. Changed. Fluid.",
        "My skin shimmered like scales. My blood was saltwater.",
        "I could command the waves. Call the rain.",
        "But my island was gone. Swallowed by the storm.",
        "The Void had taken it. The black waves were not natural.",
        "I swore vengeance. Not a hot, burning vengeance like Fire.",
        "But a cold, relentless pressure. Like the deep ocean.",
        "I will erode their defenses. I will drown their darkness.",
        "I met the others. They are loud. Chaotic.",
        "Fire is impulsive. He burns bright but fast.",
        "I am the counterweight. The patience. The flow.",
        "Water yields, but it conquers. It goes around, or through.",
        "Nothing can stop the river from reaching the sea.",
        "I teach them to adapt. To be formless.",
        "To crash when necessary, but to retreat when needed.",
        "Healing is my gift. Water cleanses. It restores.",
        "I wash away their pain. I mend their wounds.",
        "But do not mistake my gentleness for weakness.",
        "A tsunami is water. A glacier is water.",
        "I can be as hard as ice, as furious as the storm.",
        "The Void hates the water. It cannot grasp it.",
        "We slip through their fingers. We surround them.",
        "I miss the silence of the deep. The weight of it.",
        "Here, on the surface, everything is so light. So fleeting.",
        "But I have a duty. To the lost island. To the sea.",
        "I carry the ocean within me. Every drop is a memory.",
        "I remember the songs of the whales. The dance of the dolphins.",
        "They are gone now. Hiding from the darkness.",
        "I will make the waters safe again.",
        "I will purify the corrupted streams.",
        "My friends rely on me. I am their sustenance.",
        "Without water, life withers. Fire dies. Plants fade.",
        "I am the connector. The blood of the world.",
        "Sometimes I feel like I am drowning in the responsibility.",
        "But then I look at Plant. He grows because of me.",
        "I look at Ice. He is my brother, frozen in time.",
        "We are two sides of the same coin. Motion and stillness.",
        "I flow. He stands.",
        "Together, we control the temperature of the battle.",
        "The enemy tries to poison the wells. To taint the source.",
        "I filter it out. I keep us pure.",
        "My philosophy is simple: Keep moving.",
        "Stagnant water breeds disease. Flowing water brings life.",
        "I must not stop. I must not settle.",
        "I am the river. I am the rain.",
        "I am the tear on a cheek. The sweat on a brow.",
        "I am in every living thing.",
        "That connects me to everyone. To everything.",
        "I feel their thirst. Their need.",
        "It drives me. It gives me purpose.",
        "The Void is dry. It is a desert of the soul.",
        "I will bring the flood.",
        "I will wash them away.",
        "Clean slate. A new beginning.",
        "That is what water offers. Rebirth.",
        "Baptism by the storm.",
        "I am ready to turn the tide.",
        "The moon guides me. The stars reflect in me.",
        "I am vast. I am deep.",
        "Do not test the depth of my resolve.",
        "You will find only pressure.",
        "Crushing, unyielding pressure.",
        "And then, silence.",
        "The peace of the abyss.",
        "I fight for that peace.",
        "For the calm after the storm.",
        "For the blue horizon.",
        "I am Water. And I am rising.",
        "The dam is breaking.",
        "Let the river run wild.",
        "Let the ocean reclaim its own.",
        "We are the wave.",
        "And we are crashing down.",
        "Prepare yourself.",
        "The tide is coming in.",
        "And it will not be stopped."
    ],
    ice: [
        "Silence. That is the first thing I remember. Pure silence.",
        "I lived in the high peaks. Where the air is thin and sharp.",
        "The world below was noisy. Chaotic. I preferred the quiet.",
        "I was a monk. A seeker of stillness.",
        "I meditated on the nature of time. Of preservation.",
        "Ice is not death. It is a pause. A breath held forever.",
        "I sought to stop the decay of the world.",
        "To capture perfection and hold it in crystal.",
        "The Void came not as a darkness, but as a rot.",
        "It withered the flowers. It crumbled the stone.",
        "I could not stand it. The disorder. The entropy.",
        "I reached out to the glacier. I asked for its strength.",
        "It answered. It froze my heart.",
        "Not in cruelty, but in clarity.",
        "I stopped aging. I stopped feeling the cold.",
        "I became the cold.",
        "My emotions cooled. Fear, anger, joy... they slowed down.",
        "I see things logically now. Calculated. Precise.",
        "Fire is my opposite. He is all emotion. All chaos.",
        "He burns through life. I preserve it.",
        "We clash, but we need each other.",
        "He melts the path; I solidify the ground.",
        "Water is my kin, but he is too fluid. Too changing.",
        "I give him structure. I give him form.",
        "I create barriers. Walls of diamond-hard frost.",
        "I protect by stopping. By halting the enemy's advance.",
        "They charge, and I turn them to statues.",
        "Monuments to their own foolishness.",
        "I fight with precision. One strike. One shatter.",
        "I do not waste energy. Entropy is the enemy.",
        "I conserve. I wait.",
        "The perfect moment is worth waiting for.",
        "My friends think I am unfeeling. A statue myself.",
        "They are wrong. I feel deeply.",
        "But I feel in slow motion. A grief that lasts a century.",
        "A joy that sparkles like a snowflake, unique and fleeting.",
        "I cherish these moments. I lock them away in my mind.",
        "A library of frozen memories.",
        "I remember the blue of the sky on the highest peak.",
        "The sound of the wind howling through the pass.",
        "The solitude. It was beautiful.",
        "But solitude is not enough anymore.",
        "The Void threatens to consume everything. To make it nothing.",
        "I cannot freeze nothing. I need something to preserve.",
        "So I fight. To save the world so I can freeze it later.",
        "A joke. I am capable of humor. It is just... dry.",
        "Like the air at the summit.",
        "Plant understands me. He knows the cycle of seasons.",
        "Winter is necessary. It is the rest before the growth.",
        "I am the Winter. I bring the sleep.",
        "The enemy fears the cold. It slows them down.",
        "It makes them brittle. Weak.",
        "I exploit that weakness. I snap them like twigs.",
        "My power is absolute zero. The cessation of all movement.",
        "In that stillness, there is truth.",
        "No lies can hide in the ice. It is transparent.",
        "I see through their deceptions.",
        "I see the fear in their hearts. I freeze it there.",
        "I am the architect of the battlefield.",
        "I shape the terrain. I control the flow.",
        "I am the wall that does not break.",
        "I am the spear that pierces the soul.",
        "Sometimes I worry that I will freeze completely.",
        "That I will stop moving, stop thinking.",
        "Become just another glacier.",
        "But then Fire laughs, or Water splashes me.",
        "And I remember I am alive. I am part of this flow.",
        "I am the anchor. The steady point.",
        "When the world spins out of control, I hold it together.",
        "I am the crystal clarity in the fog of war.",
        "Trust in the ice. It will not fail you.",
        "It is strong. It is pure.",
        "I am Ice. And I am eternal.",
        "The cold is a gift. Embrace it.",
        "Let it numb the pain. Let it sharpen the mind.",
        "We are the blizzard.",
        "We are the avalanche.",
        "Inescapable. Inevitable.",
        "The world will turn. The seasons will change.",
        "But the ice remains.",
        "Watching. Waiting.",
        "Preserving.",
        "I am the guardian of the moment.",
        "And I will not let this moment fade.",
        "Stay frosty, my friends.",
        "The winter is here.",
        "And it is beautiful."
    ],
    plant: [
        "I hear them. The roots. The leaves. The mycelium.",
        "They are always talking. A constant hum of life.",
        "I was a gardener once. In a concrete city.",
        "I tried to bring green to the grey. To heal the scars.",
        "People walked by, blind to the miracle of a sprouting seed.",
        "But I saw. I felt the struggle of the sapling.",
        "The Void came as a blight. A grey rot.",
        "It silenced the songs of the trees.",
        "I wept. My tears watered the last flower.",
        "And the flower spoke back.",
        "It offered me a bargain. My humanity for their survival.",
        "I accepted. I became the Green.",
        "My skin turned to bark. My hair to vines.",
        "I can feel the sun on my leaves. It is delicious.",
        "I can feel the water in the soil. It is life.",
        "I am never alone. The forest is with me.",
        "I fight for the small things. The moss. The beetle.",
        "They are the foundation of everything.",
        "Fire scares me. He is destruction incarnate.",
        "But he is also renewal. The forest needs fire to be reborn.",
        "We have a difficult relationship. A balance of terror and necessity.",
        "Water is my love. My sustenance.",
        "Without him, I am dust. With him, I am a jungle.",
        "We dance together. Growth and flow.",
        "Ice... Ice is a hard sleep. A long wait.",
        "I respect him. He tests my endurance.",
        "Metal is strange. He is of the earth, but refined. Dead.",
        "Yet he protects. He is the trellis I climb.",
        "We are a garden. Diverse. Wild.",
        "I bring the healing. The regeneration.",
        "I can mend flesh as easily as I mend a branch.",
        "Life wants to live. It is stubborn.",
        "I channel that stubbornness. That will to survive.",
        "The enemy is anti-life. They are the concrete.",
        "I will crack them. I will grow through them.",
        "My vines are strong. They strangle the darkness.",
        "My thorns are sharp. They protect the bloom.",
        "I am the slow crush of nature.",
        "You cannot stop the spring.",
        "I am patient. I can wait for centuries.",
        "But I can also be sudden. A bloom in the desert.",
        "I use poisons. Spores. The weapons of the wild.",
        "Nature is not just beautiful. It is cruel.",
        "It is survival of the fittest.",
        "And we are the fittest.",
        "I remember the smell of rain on dry earth.",
        "The taste of a ripe berry.",
        "These are the things worth fighting for.",
        "The simple joys of existence.",
        "The Void offers nothing. Only emptiness.",
        "I offer abundance. Growth. Chaos of life.",
        "I am the forest that walks.",
        "I am the wrath of the wild.",
        "Do not underestimate a flower.",
        "It can break a stone.",
        "I am the root and the branch.",
        "I connect the earth to the sky.",
        "I ground the team. I keep them nourished.",
        "I absorb their pain and turn it into strength.",
        "Composting the bad to grow the good.",
        "That is the cycle. That is the way.",
        "Death is just a stage. A transformation.",
        "I do not fear it. I will just become soil.",
        "And from that soil, new life will rise.",
        "But not today. Today I fight.",
        "I summon the treants. The spirits of the wood.",
        "They are angry. They want their world back.",
        "We will reclaim it. Inch by inch.",
        "Root by root.",
        "The world will be green again.",
        "I promise you that.",
        "Listen to the wind in the leaves.",
        "It is a war cry.",
        "We are growing.",
        "We are blooming.",
        "We are here.",
        "I am Plant. And I am life.",
        "Unstoppable life.",
        "Let us grow together.",
        "Into a mighty forest.",
        "That no darkness can fell."
    ],
    metal: [
        "Clang. Clang. Clang. The rhythm of the forge.",
        "I was a blacksmith. A shaper of tools. Of weapons.",
        "I understood the metal. The grain. The temper.",
        "It has a voice. A high, singing ring.",
        "I sought perfection. The unbreakable blade.",
        "The impenetrable shield.",
        "I worked the steel until my hands were hard as iron.",
        "The Void came with weapons of shadow. Intangible.",
        "My steel passed through them. Useless.",
        "I needed something more. I needed to BE the steel.",
        "I fused myself with my masterpiece.",
        "A suit of armor, animated by will alone.",
        "I gave up the flesh. The weakness. The pain.",
        "Now I am the bulwark. The wall.",
        "I feel no pain. Only impact.",
        "I do not bleed. I dent.",
        "And dents can be hammered out.",
        "I am the anchor of the team.",
        "When they are pushed back, I stand firm.",
        "I hold the line.",
        "Fire heats me up. Makes me malleable.",
        "It is dangerous, but it allows me to change shape.",
        "To adapt to the battle.",
        "Ice makes me brittle, but hard. Razor sharp.",
        "Water rusts me if I am not careful. I must keep moving.",
        "Plant... he grows over me. Decorates me.",
        "It is annoying, but... comforting. Like moss on a statue.",
        "I am the technology. The industry.",
        "I bring order to the chaos of nature.",
        "Precision. Calculation. Geometry.",
        "My attacks are measured. Efficient.",
        "I do not waste movement.",
        "I am a machine of war. Built for this purpose.",
        "But inside the shell, there is still a ghost.",
        "I remember the heat of the forge. The sweat.",
        "The satisfaction of a job well done.",
        "I miss the taste of bread. The touch of skin.",
        "But I sacrificed that for strength.",
        "For the power to protect.",
        "I am the shield that guards the realms.",
        "I attract the enemy. I draw their fire.",
        "Let them break themselves upon me.",
        "I am the anvil. Let them be the hammer.",
        "They will shatter.",
        "I use magnets. Electricity. The forces of the earth.",
        "I control the battlefield with invisible hands.",
        "I pull the enemy in. I push them away.",
        "I am the master of magnetism.",
        "The Void has no substance. No weight.",
        "I am all substance. All weight.",
        "I ground the reality. I make it solid.",
        "I will not let the world dissolve.",
        "I will rivet it together.",
        "Bolt it down.",
        "Weld the cracks.",
        "I am the Iron Will.",
        "The Steel Resolve.",
        "My friends are soft. Squishy.",
        "They need armor. I am that armor.",
        "I surround them with floating shields.",
        "I take the hits meant for them.",
        "It is my duty. My function.",
        "And I function perfectly.",
        "I am upgrading constantly.",
        "Better alloys. Faster servos.",
        "I will never be obsolete.",
        "The enemy evolves, so must I.",
        "I am the cutting edge.",
        "The heavy metal.",
        "Listen to the sound of my steps.",
        "Like thunder. Like doom.",
        "I am coming for you, darkness.",
        "And I am heavy.",
        "You cannot move me.",
        "You cannot break me.",
        "I am Metal. And I am eternal.",
        "Steel yourself.",
        "The hammer falls.",
        "And I am the hand that holds it.",
        "Forged in fire.",
        "Tempered in ice.",
        "Polished by water.",
        "Grounded by earth.",
        "I am the ultimate weapon.",
        "And I fight for the light."
    ]
};
